from enum import Enum

# Game
GAME_NAME = "Untouchable"
GAME_SPEED = 15
FONT_SIZE = 36
SCREEN_WIDTH = 1400
SCREEN_HEIGHT = 900
SCREEN_CENTER_POS = (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2)
SCREEN_CENTER_POS_X = SCREEN_WIDTH // 2
SCREEN_CENTER_POS_Y = SCREEN_HEIGHT // 2
SCORE_DISPLAY_LOC = (10, 10)
TIME_DISPLAY_LOC = (10, FONT_SIZE+10)

# Buttons
MENU_BUTTON_WIDTH = 100
MENU_BUTTON_HEIGHT = 60
RESTART_BUTTON_LOC = (SCREEN_CENTER_POS_X - MENU_BUTTON_WIDTH, SCREEN_CENTER_POS_Y)
QUIT_BUTTON_LOC = (SCREEN_CENTER_POS_X + MENU_BUTTON_WIDTH, SCREEN_CENTER_POS_Y)

# Player
PLAYER_SIZE = (50, 50)
PLAYER_STARTING_TIME = 10
PLAYER_SPEED = 5

# Enemy
ENEMY_NUM = 25
ENEMY_SIZE = (20, 20)
ENEMY_SPEED_MIN = 1
ENEMY_SPEED_MAX = 4
ENEMY_SPAWN_TOP = 'top'
ENEMY_SPAWN_BOTTOM = 'bottom'
ENEMY_SPAWN_LEFT = 'left'
ENEMY_SPAWN_RIGHT = 'right'
ENEMY_SPAWN_POS = [
    ENEMY_SPAWN_TOP,
    ENEMY_SPAWN_BOTTOM,
    ENEMY_SPAWN_LEFT,
    ENEMY_SPAWN_RIGHT
]

# Time Pack
TIMEPACK_SIZE = (25, 25)
TIMEPACK_VALUE = 5
TIMEPACK_NUM = 1

# Colors
WHITE = (255, 255, 255)
GRAY = (150, 150, 150)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)

# Q-Learning Parameters
LEARNING_RATE = 0.1
DISCOUNT_FACTOR = 0.9
EXPLORATION_RATE = 0.1
NUM_STATES = SCREEN_WIDTH * SCREEN_HEIGHT * (ENEMY_NUM + 1)
NUM_ACTIONS = 4  # Up, Down, Left, Right

# Directions as enums
class Directions(Enum):
    RIGHT = 1
    LEFT = 2
    UP = 3
    DOWN = 4
